"""Original source cards from the user-authorized Drive review. No book text bundled."""
SOURCES = [{'id': '1TQssqQK2m-TUtdLLLhfPqqpazILzmdoo',
  'title': 'Empirical Market Microstructure',
  'author': 'Joel Hasbrouck',
  'year': 2007,
  'section': 'Ch. 8; Ch. 14.2, pp. 144–145',
  'topics': 'spread execution commissions delay partial fills implementation shortfall',
  'summary': 'Preserve bid, ask, midpoint and timestamps at decision and arrival; measure signed fill costs '
             'and unfilled quantities.',
  'limitations': 'Market institutions in a 2007 text require contemporary verification.',
  'claim_type': 'execution measurement',
  'horizon': 'intraday',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1TQssqQK2m-TUtdLLLhfPqqpazILzmdoo/view',
  'content_sha256': '840bafdca8feda919bde48c95b5f60407bd1f81a3b443cbb26c62edd8adc03b2',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1dQa_gizCk5u34d0Lg9BF_HROnMoOmXc7',
  'title': 'Python for Algorithmic Trading Cookbook',
  'author': 'Jason Strimpel',
  'year': 2024,
  'section': 'Chs. 5–9; Ch. 11',
  'topics': 'factor backtest event orders evaluation',
  'summary': 'Separate factor discovery from event-based fill simulation; retain order lifecycle and '
             'economic metrics.',
  'limitations': 'Recipes are examples, not a validated broker adapter; some sample data ends in 2018.',
  'claim_type': 'methodology',
  'horizon': 'intraday and multi-day',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1dQa_gizCk5u34d0Lg9BF_HROnMoOmXc7/view',
  'content_sha256': '025aa9e3e36677b4c12404d77f5ddaa171eaec1d8aa97ebd994733f1a6a645bb',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1CluvVjLiB07-DGJnIgCWh4feXS2FZfw1',
  'title': 'Quantitative Trading Strategies Using Python',
  'author': 'Peng Liu',
  'year': 2023,
  'section': 'Ch. 7; Ch. 9',
  'topics': 'bias survivorship optimization transaction costs walk forward',
  'summary': 'Retain every tested variant, use historical membership, and reserve future evidence beyond '
             'optimization.',
  'limitations': 'Current surviving tickers are not a point-in-time universe. Optimization can select chance '
                 'winners.',
  'claim_type': 'methodology',
  'horizon': 'multi-horizon',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1CluvVjLiB07-DGJnIgCWh4feXS2FZfw1/view',
  'content_sha256': '3a30d4dcc2c549d362f70a548e3eed4c7cb9d680b7a28088bf68aa40089afa40',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1764PTS0X0Otkv8EyjPcD4urdtjmp-6Wi',
  'title': 'Build a Robo-Advisor with Python',
  'author': 'Rob Reider and Alex Michalka',
  'year': 2025,
  'section': 'Ch. 3; Ch. 7',
  'topics': 'portfolio covariance sector correlation valuation risk',
  'summary': 'Assess combined exposure and compare active returns with cash and market exposure.',
  'limitations': 'Longer-term portfolio context does not establish intraday alpha.',
  'claim_type': 'portfolio context',
  'horizon': 'longer-term',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1764PTS0X0Otkv8EyjPcD4urdtjmp-6Wi/view',
  'content_sha256': '23c2080932b1d31f0b2ea56a33ab7be2bdc31a4a4ed5af1925a7e4831d85dd0b',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1tJs6IydiA9y2ayikCVs1nUBa7H0jAwpR',
  'title': 'AI Engineering',
  'author': 'Chip Huyen',
  'year': 2025,
  'section': 'Chs. 5–6',
  'topics': 'memory retrieval sources evaluation hallucination latency cost',
  'summary': 'Use retrievable source cards and frozen judgment cases; evaluate stale facts, tool inputs and '
             'confidence with cost and latency.',
  'limitations': 'Retrieval knowledge, statistical ranking weights and neural-model fine-tuning are '
                 'distinct.',
  'claim_type': 'AI engineering',
  'horizon': 'research workflow',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1tJs6IydiA9y2ayikCVs1nUBa7H0jAwpR/view',
  'content_sha256': '3e0a2ed44e368a3e4fdcf405e61a3694865d1ab876f53e34dad1379182270637',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1e-pia-5JaQvKSoGUWGBHWiGiyBJj26Sv',
  'title': 'The Volume Factor',
  'author': 'Buff Pelz Dormeier',
  'year': 2024,
  'section': 'Ch. 3; Ch. 5',
  'topics': 'volume pullback stabilization buyers liquidity sale',
  'summary': 'Treat relative volume with price stabilization as a testable confirmation hypothesis. Match '
             'elapsed session windows.',
  'limitations': 'Volume spikes also accompany selling. Author-reported hypothetical backtests are not app '
                 'outcomes.',
  'claim_type': 'hypothesis',
  'horizon': 'intraday and swing',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1e-pia-5JaQvKSoGUWGBHWiGiyBJj26Sv/view',
  'content_sha256': 'b0ecbf6c2d1bcc7d905e83e16cef61108d04297e8a5708dd603c416d6a3fa4a9',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '19tswKFw3upbPCdSGoM1YNl4NKo66TOER',
  'title': 'Deep Learning for Finance',
  'author': 'Sofien Kaabar',
  'year': 2024,
  'section': 'Ch. 7, pp. 184–193',
  'topics': 'forecast metrics baseline accuracy profit factor overfitting',
  'summary': 'Compare forecasts with persistence and no-skill baselines; measure net economic results, '
             'gains, losses and drawdown.',
  'limitations': 'Accuracy and RMSE alone do not establish tradable profitability.',
  'claim_type': 'methodology',
  'horizon': 'multi-horizon',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/19tswKFw3upbPCdSGoM1YNl4NKo66TOER/view',
  'content_sha256': 'c6890d5c973542d7ef8844aa8f984d2db1d0add00f1bd13b752df4edca50727b',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1_E5bhEf6ybILNp59Lkhv-57jIKKOkNJ3',
  'title': 'Algorithmic Trading Systems and Strategies',
  'author': 'Viktoria Dolzhenko',
  'year': 2024,
  'section': 'Ch. 2, pp. 59–60',
  'topics': 'benchmark cash buy hold portfolio return',
  'summary': 'Compare active results with cash and appropriate market exposure over matched dates, capital '
             'and risk.',
  'limitations': 'Mean isolated trade outcomes are not portfolio returns.',
  'claim_type': 'methodology',
  'horizon': 'multi-horizon',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1_E5bhEf6ybILNp59Lkhv-57jIKKOkNJ3/view',
  'content_sha256': '205685862c8519b54b8763715af7d1a6c3b46d13959d39e6c53275f782a5f803',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '18NXoM4_0hqEWkM3zeqWWxTlaAxR5h9pm',
  'title': 'Advanced Options Trading',
  'author': 'Kevin Kraus',
  'year': 2010,
  'section': 'pp. 20–29',
  'topics': 'option volatility greeks time decay premium scenarios',
  'summary': 'Separate the underlying thesis from contract value; stress price, time and volatility '
             'independently.',
  'limitations': 'Older examples; theoretical prices are not executable. Exercise and assignment require '
                 'explicit modeling.',
  'claim_type': 'pricing framework',
  'horizon': 'options multi-horizon',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/18NXoM4_0hqEWkM3zeqWWxTlaAxR5h9pm/view',
  'content_sha256': 'c26f140f4b7d625117886e251dcc651d6cbe0aa25bfadf763a43d41307194c56',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1_Zn2Ju7X2wXbFv9HWYOL7gVcDhnFGhh2',
  'title': 'Advanced Swing Trading',
  'author': 'John Crane',
  'year': 2003,
  'section': 'Entry, protective-stop and monitoring passages',
  'topics': 'swing pullback stop invalidation entry horizon',
  'summary': 'State entry conditions, invalidation and holding period before testing a pullback.',
  'limitations': 'A retrospectively identified bottom is not an observable real-time signal. Patterns need '
                 'independent tests.',
  'claim_type': 'hypothesis',
  'horizon': 'swing',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1_Zn2Ju7X2wXbFv9HWYOL7gVcDhnFGhh2/view',
  'content_sha256': '222846e93d687ce6942410b09d7b4f2a3f96629180987d2de11eb370f4d2cc5a',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '157-XCg3k7dTuNbH0aSaHIWmnHfLNNeNi',
  'title': 'Python for Algorithmic Trading Cookbook, 2nd edition (early access)',
  'author': 'Jason Strimpel',
  'year': 2025,
  'section': 'Available Chapters 1–2 only',
  'topics': 'python data sources early access',
  'summary': 'Use only the chapters actually present; retain this edition separately from the complete 2024 '
             'edition.',
  'limitations': 'The table of contents lists later chapters that are absent. The companion ZIP was not '
                 'reviewed.',
  'claim_type': 'limited reference',
  'horizon': 'research workflow',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/157-XCg3k7dTuNbH0aSaHIWmnHfLNNeNi/view',
  'content_sha256': '96361ee303f54d28232e18a358b0533e3a636c3874af105482681b51991b8b1b',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'},
 {'id': '1p0GVfIjbkoeax6ZEpcobUW7Yh4n-3Zn2',
  'title': 'From Data to Trade',
  'author': 'Gautier Marti and ChatGPT',
  'year': 2022,
  'section': 'Front matter and selected sections',
  'topics': 'machine learning AI generated verification',
  'summary': 'Use its topic list to formulate questions for independent sources.',
  'limitations': 'Explicit AI-generated publishing experiment. Claims need independent corroboration. '
                 'Filename year differs from first release.',
  'claim_type': 'low-confidence reference',
  'horizon': 'research workflow',
  'instruments': 'US equities / standard equity options where relevant',
  'url': 'https://drive.google.com/file/d/1p0GVfIjbkoeax6ZEpcobUW7Yh4n-3Zn2/view',
  'content_sha256': '87adde01291bdaf3b1bb9ba5ae49d5d4a3fe5a8a62aebb2ed782abc93b394627',
  'hash_scope': 'locally extracted review text',
  'verification_status': 'selected sections reviewed; claims not strategy validation',
  'reviewed_at': '2026-09-23'}]
