const assert=require('node:assert/strict');
const {agentView}=require('../static/live_agent.js');
const agent={configured:true,enabled:true,mode:'auto_live',session_active:true,market_open:true,phase:'enabled'};
const desk={broker:{connected:true},broker_book:{ok:true,risk_ready:true,day_pnl_usd:0},broker_ledger:{pending_broker_orders:[]}};
const view=(a={},s=desk,age=0,agentAge=0)=>agentView({...agent,...a},s,age,agentAge);
assert.equal(view().label,'Monitoring');
assert.equal(view({phase:'researching'}).label,'Researching');
assert.equal(view({market_open:false}).label,'Waiting for market');
assert.equal(view({},null).label,'Checking account');
assert.equal(view({},desk,26000).label,'Checking account');
assert.equal(view({},desk,0,26000).label,'Status unavailable');
assert.equal(view({enabled:false}).label,'Paused');
assert.equal(view({session_active:false}).label,'Paused');
assert.equal(view({phase:'budget',message:'Budget reached'}).label,'Research paused');
assert.equal(view({}, {...desk,broker_book:{ok:true,risk_ready:false,day_pnl_usd:null}}).label,'New entries blocked');
assert.equal(view({}, {...desk,broker:{connected:false}}).label,'Connection needed');
assert.equal(view({}, {...desk,broker_ledger:{pending_broker_orders:[{}]}}).label,'Reconciling order');
assert.doesNotMatch(JSON.stringify(view()),/Ready to trade/);
console.log('Agent readiness: current connection, market, P&L, orders, worker phase and stale data remain distinct.');
